import { BarChart3, BriefcaseBusiness, Bot, CircleUserRound, Database, Eye, EyeOff, LogOut, RefreshCw, ShieldCheck } from "lucide-react";
import type { ReactNode } from "react";
import { Button } from "@/shared/ui/button";
import { cn } from "@/shared/lib/utils";
export type Page = "overview" | "holdings" | "position" | "agent" | "profile";
const nav = [
  { page: "overview", label: "组合概览", icon: BarChart3 },
  { page: "holdings", label: "全部持仓", icon: BriefcaseBusiness },
  { page: "agent", label: "Agent 观察", icon: Bot },
  { page: "profile", label: "我的", icon: CircleUserRound },
] as const;
export function Shell({ page, onNavigate, phone, health, amountsVisible, onToggleAmounts, onRefresh, onLogout, children }: { page: Page; onNavigate: (page: Page) => void; phone: string; health: string; amountsVisible: boolean; onToggleAmounts: () => void; onRefresh: () => void; onLogout: () => void; children: ReactNode }) {
  return <div className="min-h-screen md:flex"><aside className="hidden w-60 shrink-0 flex-col bg-[#19314a] p-5 text-slate-200 md:flex"><div className="flex items-center gap-3 border-b border-white/10 pb-7 text-base font-bold text-white"><span className="rounded-lg bg-white/10 p-2"><ShieldCheck className="h-5 w-5" /></span>Portfolio Agent</div><p className="mb-3 mt-8 px-3 text-[10px] font-bold tracking-[.2em] text-slate-400">WORKSPACE</p><nav aria-label="主导航" className="space-y-1">{nav.map(({ page: item, label, icon: Icon }) => <button key={item} onClick={() => onNavigate(item)} className={cn("flex w-full items-center gap-3 rounded-lg px-3 py-3 text-left text-sm transition-colors hover:bg-white/10", page === item || (page === "position" && item === "holdings") ? "bg-white/15 text-white" : "text-slate-300")}><Icon className="h-4 w-4" />{label}</button>)}</nav><div className="mt-auto rounded-xl border border-white/10 p-4 text-xs text-slate-400"><ShieldCheck className="mb-2 h-5 w-5 text-sky-200" />规则计算与证据引用由服务端负责。</div><button className="mt-5 flex items-center justify-between border-t border-white/10 pt-5 text-xs" onClick={onLogout}><span>{phone}</span><LogOut className="h-4 w-4" /></button></aside><div className="min-w-0 flex-1"><header className="flex h-16 items-center justify-between gap-2 border-b bg-white px-4 md:px-8"><div className="flex items-center gap-2 text-xs text-muted-foreground"><Database className="h-4 w-4" /><span>{health === "ready" ? "API 已连接" : health === "offline" ? "API 未连接" : "正在检测 API"}</span></div><div className="flex items-center gap-1"><Button size="icon" variant="ghost" aria-label={amountsVisible ? "隐藏金额" : "显示金额"} title={amountsVisible ? "隐藏金额" : "显示金额"} onClick={onToggleAmounts}>{amountsVisible ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</Button><Button size="icon" variant="ghost" aria-label="刷新数据" title="刷新数据" onClick={onRefresh}><RefreshCw className="h-4 w-4" /></Button><Button size="icon" variant="ghost" className="md:hidden" aria-label="退出登录" onClick={onLogout}><LogOut className="h-4 w-4" /></Button></div></header><main className="mx-auto max-w-7xl p-5 pb-24 md:p-9">{children}</main></div><nav aria-label="移动导航" className="fixed inset-x-0 bottom-0 z-30 grid grid-cols-4 border-t bg-white/95 p-2 backdrop-blur md:hidden">{nav.map(({ page: item, label, icon: Icon }) => <button key={item} onClick={() => onNavigate(item)} className={cn("flex flex-col items-center gap-1 rounded-lg py-1 text-[10px]", page === item || (page === "position" && item === "holdings") ? "text-primary" : "text-muted-foreground")}><Icon className="h-5 w-5" />{label}</button>)}</nav></div>;
}
